import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}

/**
 * cara namain file komponen halaman udh diatur :
 * - page.tsx
 * - layout.tsx
 * - sisanya check di dokumentasinya : https://nextjs.org/docs/app/building-your-application/routing
 *    - kalo liat dokumentasi next perhatiin lagi liat yg app router ato pages router
 *    - pages router itu yg versi lama
 * - routing nya file-based
 *    - tinggal bikin directory baru trus bikin page.tsx di dlmnya
 *    - nama directory jadi path urlnya (kalo directorynya nested brarti url nya jg nested)
 *    - kalo bikin layout.tsx di dlm directory yg dalem, nanti bakal dirender jga di dlm layout dari directory yg lebih luar
 *
 * page.tsx bakal dirender di sebagai children dlm layout
 * kalo mau bikin folder / directory utk reusable components bisa dibuat di root directory
 */
